Fix workflow

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -14,6 +14,7 @@ jobs:
 
     permissions:
       contents: write
+      pages: read
 
     environment:
       name: github-pages
@@ -52,3 +53,17 @@ jobs:
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./docs/target/generated-docs/
+
+    - name: Get GitHub Pages URL
+      id: deployment
+      if: ${{ github.ref == 'refs/heads/main' }}
+      env:
+        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      shell: bash
+      run: |
+        page_url="$(gh api "repos/${GITHUB_REPOSITORY}/pages" --jq '.html_url')"
+        if [[ -z "$page_url" || "$page_url" == "null" ]]; then
+          echo "::error::GitHub Pages URL is not configured."
+          exit 1
+        fi
+        printf 'page_url=%s\n' "$page_url" >> "$GITHUB_OUTPUT"
